package ch.jass.connection.inbound;

public enum RequestMessageType {
	REQUEST_PLAYER_NAME,
	REQUEST_SESSION_CHOICE,
	BROADCAST_SESSION_JOINED,
	BROADCAST_TEAMS,
	DEAL_CARDS,
	REQUEST_TRUMPF,
	BROADCAST_TRUMPF,
	REQUEST_CARD,
	REJECT_CARD,
	PLAYED_CARDS,
	BROADCAST_STICH,
	BROADCAST_GAME_FINISHED,
	BROADCAST_WINNER_TEAM
}
